# Após encontrar todos os tags <a> com a class 'internal-link',
# vamos copiar todo esse links e colocar em uma variável
# para utilizar no algoritmo de baixar os arquivos
links = (
    """<a class="internal-link"
    data-mce-href="resolveuid/f710899c6c7a485ea62a1acc75d86c8c" """
    """data-mce-style="" """
    """data-tippreview-enabled="true" """
    """data-tippreview-image="" """
    """data-tippreview-title=""
    href="https://www.gov.br/ans/pt-br/acesso-a-informacao/participacao-da-sociedade/atualizacao-do-rol-de-procedimentos/Anexo_I_Rol_2021RN_465.2021_RN627L.2024.pdf"
    """
    """style="" target="_blank" title="">Anexo I.</a>, """
    """<a class="internal-link"
    data-mce-href="resolveuid/aee04d07eec1412e8121f50c277d72b9" """
    """data-mce-style="" """
    """data-tippreview-enabled="true" """
    """data-tippreview-image="" """
    """data-tippreview-title=""
    href="https://www.gov.br/ans/pt-br/acesso-a-informacao/participacao-da-sociedade/atualizacao-do-rol-de-procedimentos/Anexo_I_Rol_2021RN_465.2021_RN627L.2024.xlsx"""
    """style="" target="_blank" title="">(Anexo I</a>, """
    """<a class="internal-link"
    data-mce-href="resolveuid/85adaa3de5464d8aadea11456bfb4f94" """
    """data-mce-style="" """
    """data-tippreview-enabled="true" """
    """data-tippreview-image="" """
    """data-tippreview-title=""
    href="https://www.gov.br/ans/pt-br/acesso-a-informacao/participacao-da-sociedade/atualizacao-do-rol-de-procedimentos/Anexo_II_DUT_2021_RN_465.2021_RN628.2025_RN629.2025.pdf"
    """
    """style="" target="_blank" title="">Anexo II.</a>, """
    """<a class="internal-link" """
    """data-mce-href="resolveuid/26bf4441cb3d4b48a26f59185e90f953" """
    """data-tippreview-enabled="false" data-tippreview-image="" """
    """data-tippreview-title=""
    href="https://www.gov.br/ans/pt-br/arquivos/assuntos/consumidor/o-que-seu-plano-deve-cobrir/nota13_geas_ggras_dipro_17012013.pdf"""
    """target="_blank" title="">Nota sobre Terminologias</a>, """
    """<a class="internal-link" """
    """data-mce-href="resolveuid/036c5ac8cbd34b859de38c69914d9141" """
    """data-mce-style="" """
    """data-tippreview-enabled="true" """
    """data-tippreview-image="" """
    """data-tippreview-title=""
    href="https://www.gov.br/ans/pt-br/acesso-a-informacao/participacao-da-sociedade/atualizacao-do-rol-de-procedimentos/CorrelaoTUSS.202409Rol.2021_TUSS202501_RN627L.2025.xlsx"""
    """style="" target="_blank" title="">Correlação TUSS x Rol </a>"""
)